// Compiled Bible Data
char *standard_books[] = {"Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy", "Joshua", "Judges", "Ruth", "1st Samuel", "2nd Samuel", "1st Kings", "2nd Kings", "1st Chronicles", "2nd Chronicles", "Ezra", "Nehemiah", "Esther", "Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah", "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi", "Matthew", "Mark", "Luke", "John", "Acts", "Romans", "1st Corinthians", "2nd Corinthians", "Galatians", "Ephesians", "Philippians", "Colossians", "1st Thessalonians", "2nd Thessalonians", "1st Timothy", "2nd Timothy", "Titus", "Philemon", "Hebrews", "James", "1st Peter", "2nd Peter", "1st John", "2nd John", "3rd John", "Jude", "Revelation"};

#define BIBLE_BOOKS 66

struct Bible {
	struct Books {
		char *name;
		int chapter;
	}books[66];
}Bible_info = {
		{{"Genesis",50},{"Exodus",40},{"Leviticus",27},{"Numbers",36},{"Deuteronomy",34},{"Joshua",24},{"Judges",21},{"Ruth",4},{"1 Samuel",31},{"2 Samuel",24},{"1 Kings",22},{"2 Kings",25},{"1 Chronicles",29},{"2 Chronicles",36},{"Ezra",10},{"Nehemiah",13},{"Esther",10},{"Job",42},{"Psalms",150},{"Proverbs",31},{"Ecclesiastes",12},{"Song of Solomon",8},{"Isaiah",66},{"Jeremiah",52},{"Lamentations",5},{"Ezekiel",48},{"Daniel",12},{"Hosea",14},{"Joel",3},{"Amos",9},{"Obadiah",1},{"Jonah",4},{"Micah",7},{"Nahum",3},{"Habakkuk",3},{"Zephaniah",3},{"Haggai",2},{"Zechariah",14},{"Malachi",4},{"Matthew",28},{"Mark",16},{"Luke",24},{"John",21},{"Acts",28},{"Romans",16},{"1 Corinthians",16},{"2 Corinthians",13},{"Galatians",6},{"Ephesians",6},{"Philippians",4},{"Colossians",4},{"1 Thessalonians",5},{"2 Thessalonians",3},{"1 Timothy",6},{"2 Timothy",4},{"Titus",3},{"Philemon",1},{"Hebrews",13},{"James",5},{"1 Peter",5},{"2 Peter",3},{"1 John",5},{"2 John",1},{"3 John",1},{"Jude",1},{"Revelation",22}}
};

//var bible = {{"Genesis",50},{"Exodus",40},{"Leviticus",27},{"Numbers",36},{"Deuteronomy",34},{"Joshua",24},{"Judges",21},{"Ruth",4},{"1 Samuel",31},{"2 Samuel",24},{"1 Kings",22},{"2 Kings",25},{"1 Chronicles",29},{"2 Chronicles",36},{"Ezra",10},{"Nehemiah",13},{"Esther",10},{"Job",42},{"Psalms",150},{"Proverbs",31},{"Ecclesiastes",12},{"Song of Solomon",8},{"Isaiah",66},{"Jeremiah",52},{"Lamentations",5},{"Ezekiel",48},{"Daniel",12},{"Hosea",14},{"Joel",3},{"Amos",9},{"Obadiah",1},{"Jonah",4},{"Micah",7},{"Nahum",3},{"Habakkuk",3},{"Zephaniah",3},{"Haggai",2},{"Zechariah",14},{"Malachi",4},{"Matthew",28},{"Mark",16},{"Luke",24},{"John",21},{"Acts",28},{"Romans",16},{"1 Corinthians",16},{"2 Corinthians",13},{"Galatians",6},{"Ephesians",6},{"Philippians",4},{"Colossians",4},{"1 Thessalonians",5},{"2 Thessalonians",3},{"1 Timothy",6},{"2 Timothy",4},{"Titus",3},{"Philemon",1},{"Hebrews",13},{"James",5},{"1 Peter",5},{"2 Peter",3},{"1 John",5},{"2 John",1},{"3 John",1},{"Jude",1},{"Revelation",22}};
//var bibleObj = {"Genesis":"50","Exodus":"40","1Leviticus":"27","Numbers":"36","Deuteronomy":"34","Joshua":"24","Judges":"21","Ruth":"4","1st Samuel":"31","2st Samuel":"24","1 Kings":"22","2 Kings":"25","1st Chronicles":"29","2st Chronicles":"36","Ezra":"10","Nehemiah":"13","Esther":"10","Job":"42","Psalms":"150","Proverbs":"31","Ecclesiastes":"12","Song of Solomon":"8","Isaiah":"66","Jeremiah":"52","Lamentations":"5","Ezekiel":"48","Daniel":"12","Hosea":"14","Joel":"3","Amos":"9","Obadiah":"1","Jonah":"4","Micah":"7","Nahum":"3","Habakkuk":"3","Zephaniah":"3","Haggai":"2","Zechariah":"14","Malachi":"4","Matthew":"28","Mark":"16","Luke":"24","John":"21","Acts":"28","Romans":"16","1st Corinthians":"16","2st Corinthians":"13","Galatians":"6","Ephesians":"6","Philippians":"4","Colossians":"4","1st Thessalonians":"5","2nd Thessalonians":"3","1st Timothy":"6","2nd Timothy":"4","Titus":"3","Philemon":"1","Hebrews":"13","James":"5","1st Peter":"5","2nd Peter":"3","1st John":"5","2nd John":"1","3rd John":"1","Jude":"1","Revelation":"22"}